baseURL = "https://anthonycastaneda.com/"
defaultContentLanguage = "en"
languageCode = "en-us"
#paginate = "7"
theme = "spectral"
title = "Anthony"
#googleAnalytics = "G-XXXXXXXXXX"

[params]
body_is_markdown = true 
copyright = "Anthony Castañeda" 
custom_css = "css/custom.css" 
description = 'Anthony, Not Tony' 
fancyTitle = "Anthony Castañeda" # title for frontpage, may include image
startbuttonLink = "#one" 
startbuttonText = "Vamos" 
#custom_sass = "bar.scss"
images = ["img/drums.png"]

[[params.menu.main]]
title = "Home"
url = '/'

[[params.menu.main]]
title = "Posts"
url = '/posts/'

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[params.one]
body = '''
I am a dad, a drummer, and an IT guy that lives in Texas.  I work in authentication currently, handling SSO. SAML, OIDC, the usual. One of my sons told me that I like computers 'too much.'  Maybe so.  I also really like mechanical keyboards, history, city planning, and messing around with static site generators. 
'''
enable = true
title = 'About Me'

[[params.one.icon]]
icon = "solid fa-terminal"
label = "Lorem"
style = "1"

[[params.one.icon]]
icon = "fa-keyboard"
label = "Ipsum"
style = "2"

[[params.one.icon]]
icon = "solid fa-city"
label = "Dolor"
style = "3"

[params.two]
enable = true

[[params.two.section]]
body = "The lake.  Or big pond."
img = "img/lake.jpg"
img_alt = "my lake"
title = 'Quiet'

[[params.two.section]]
body = 'One year my mom got me the Holy Grail for my birthday.  She chose wisely.  I was very impressed that she was able to find it.'
img = "img/grail.png"
title = 'The Holy Grail'

[[params.two.section]]
body = 'My drums.  Since moving away from Austin, I only use these to give lessons.'
img = "img/drums.png"
title = 'Drums'

[params.three]
body = '''
Nothing was ever here.
'''
enable = true
title = 'There is nothing here'

[[params.three.feature]]
body = "Nothing compares to the expense and inconvenience of vinyl. "
icon = "solid fa-record-vinyl"
title = "Music"

[[params.three.feature]]
body = "I used to work as a mechanic at a bowling alley.  I do not bowl, so it was a little boring.  If you have issues with your AMF 82-70 Pinspotter, I'm your man."
icon = "solid fa-bowling-ball"
title = "Bowling Alleys"

[[params.three.feature]]
body = """
To quote the Dread Pirate Roberts: "Life is pain.  Anyone who says differently is selling something."
"""
icon = "solid fa-heart-crack"
title = "Sad Songs"

[[params.three.feature]]
body = "As if I wasn't nerdy enough, I am also into flags. I have two flag poles on my porch."
icon = "solid fa-flag"
title = "Vexillology"

[params.cta]
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."
enable = false
title = "Arcue ut vel commodo"

[[params.cta.link]]
href = "#"
special = true
text = "Incinerate"

[[params.cta.link]]
href = "#"
special = false
text = "Unfair"

[params.contact]
address = "Did you have any feedback for me?"
body = "Send me a message."
email = "anthony@anthonycastaneda.com"
enable = false
formspree_form_id = "movqwpvp"
phone = "1 512 555 5555"
subject = "Feedback"
title = "Feedback"

[params.social]
dribble = ""
facebook = ""
github = "anthonycastaneda"
instagram = ""
mastodon = ""
twitter = ""
youtube = "@TacoAnthony"

# language specific options

[languages.en]
languageName = "English"
weight = 0

[languages.de]
languageName = "Deutsch"
weight = 10

[languages.es]
languageName = "Español"
weight = 10
